### ISSUE TITLE
Version number on published binaries

### ISSUE THREAD

**Issue by Mihara** [flwyd/adif-multitool#5]
`adifmt` is indispensible. Thank you for making it, there's literally nothing like it.

So of course I tried to automate updating it. :) Unfortunately, that's not possible based on the information your repository provides, unless I must download it *every* time I run my update script:

The executable always reports its version number as '(devel)' (in `--version`) while the github binary release is currently invariably tagged as 'latest', and apparently overwritten, if I understand the `go-build.yml` properly...

**Comment by flwyd** [comment]
Thanks for filing this issue, I'm glad you find adifmt useful!

Could you say more about how you're trying to automate updates?

I'm still figuring out how to effectively use the automatic GitHub build process, as well as the proper use of tagging to make `go install` happy.  When the latest commit is associated with a tag, I thought `go install` would show the correct version, e.g. prior to my push this weekend `adifmt version` printed `adifmt version v0.1.8-0.20230516025727-029457f65a0b` for a command installed via `go install github.com/flwyd/adif-multitool/adifmt@latest`.  However, if you install from source (e.g. `git clone https://github.com/flwyd/adif-multitool && cd adif-multitool && go install ./adifmt`) or (I think) from an `@latest` when there isn't a tag, `adifmt version` will indeed print `(devel)` as the version information.

As you pointed out, it looks like GitHub workflows were making binaries available on the "Latest" version and not on the tagged version, even when I `git push --tags` to get the code and tags uploaded at the same time.  In 490f97ae1acb5578cba0bae1b7710475c517b35b I've attempted to change this to only building on new version tags.  Next time I push a new version (hopefully soon, to implement some feature requests), we'll see if this works.

**Comment by Mihara** [comment]
> Could you say more about how you're trying to automate updates?

Installing binaries from github releases is a repeating pattern, so I have a whole script framework to deal with this by now:

`update-adifmt`:

```bash
#!/bin/bash

source "$(dirname $0)/_bash_tools.sh"

EXECFILE=$HOME/.local/bin/adifmt
REPO=flwyd/adif-multitool

if ! $(isexec $EXECFILE); then
        exit 0
fi
updating adifmt

CURRENT=$(adifmt --version | head -n 1 | awk '{print $3}')
UPSTREAM=$(release_tag $REPO)

if [ "$CURRENT" != "$UPSTREAM" ]; then
        URL=$(release_url_r $REPO 'linux-amd64$')
        wget -O $EXECFILE "$URL"
        chmod +x $EXECFILE
else
        noneed adifmt
fi
```

`_bash_tools.sh`:

```bash
#!/bin/bash

# Stolen from https://stackoverflow.com/questions/4023830/how-to-compare-two-strings-in-dot-separated-version-format-in-bash
vercomp() {
	if [[ $1 == $2 ]]; then
		return 0
	fi
	local IFS=.
	local i ver1=($1) ver2=($2)
	# fill empty fields in ver1 with zeros
	for ((i = ${#ver1[@]}; i < ${#ver2[@]}; i++)); do
		ver1[i]=0
	done
	for ((i = 0; i < ${#ver1[@]}; i++)); do
		if [[ -z ${ver2[i]} ]]; then
			# fill empty fields in ver2 with zeros
			ver2[i]=0
		fi
		if ((10#${ver1[i]} > 10#${ver2[i]})); then
			return 1
		fi
		if ((10#${ver1[i]} < 10#${ver2[i]})); then
			return 2
		fi
	done
	return 0
}

# Github releases helpers

# $1 is to be user/repo, $2 is the search string for the download url.
release_url() {
	echo $(curl -s https://api.github.com/repos/$1/releases/latest | jq -r ".assets[] | select(.browser_download_url | contains (\"$2\")) | .browser_download_url")
}
# Same but with a regexp filter
release_url_r() {
	echo $(curl -s https://api.github.com/repos/$1/releases/latest | jq -r ".assets[] | select(.browser_download_url | test (\"$2\")) | .browser_download_url")
}

# Same, but only returns filenames, should help with sorting out release number in some cases.
release_name() {
	echo $(curl -s https://api.github.com/repos/$1/releases/latest | jq -r ".assets[] | select(.name | contains (\"$2\")) | .name")
}

# Returns the release tag name for $1.
release_tag() {
	echo $(curl -s https://api.github.com/repos/$1/releases/latest | jq -r .tag_name)
}

# Generic helpers: Is a file available and executable?
isexec() {
	if [[ -f "$1" && -x $(realpath "$1") ]]; then
		true
	else
		false
	fi
}

# Same but for which X
isexecwhich() {
	EXECNAME=$(which "$1")
	if [[ -f "$EXECNAME" && -x $(realpath "$EXECNAME") ]]; then
		true
	else
		false
	fi
}

# Fetch and install a deb.
fetchdeb() {
	wget -O /tmp/pkg.deb "$1"
	sudo apt install /tmp/pkg.deb
	rm /tmp/pkg.deb
}

# Dumb shorthand
updating() {
	echo === Updating $1 ===
}

noneed() {
	echo No need to update $1
}

# push a dir, git pull in it, pop update pattern.
gitpulldir() {
	if [ -d "$1" ]; then
		updating $(basename $1)
		pushd $1 >/dev/null
		git pull
		popd >/dev/null
	fi
}
```

There's an `update-xxxx` for every X installed this way, dealing with its quirks (parsing out version number, etc). But this approach inevitably requires that:

1. The program report an actual version number.
2. That version number be matchable to a github release tag after some massaging.

Binaries built for `adifmt` currently don't do 1 and github repo itself doesn't do 2.

**Comment by flwyd** [comment]
After a couple rabbit hole adventures, I've learned the following:

* My attempted fix to the GitHub workflow didn't work; the release workflow is configured to do "prerelease"/latest builds.  It's also out of date, and it may be prudent to switch to a different releaser action.
* I think I want to split the build and release workflows.  Build + test should run on each commit and PR, but release should only happen on semver-shaped tags.
* `adifmt version` prints `(devel)` if you build from source that's checked out locally (which is what the GitHub workflow is doing), but it prints the appropriate version tag if you install it via `go install github.com/flwyd/adif-multitool/adifmt@latest`.  The [runtime/debug.BuildInfo](https://pkg.go.dev/runtime/debug#BuildInfo) docs don't explain this very well.
  * golang/go#37475 added VCS info to build info, including the SHA and dirty state of locally but not including tags.
  * There are a lot of potential corner cases with embedding tags (like what happens if the local repo has different tags than the origin), so it seems unlikely that the Go team will add that feature.
  * The popular way to embed the version info from a GitHub action is using `go build -ldflags` to set a `version` variable.  I think I'll do that; TBD whether the version var or runtime info should take precedence.  Printing `Main.Sum` from runtime in addition to the friendly semantic version is probably also useful.

I recognize that `go install` isn't how the shell scripts above work, but if you want an accurate version tag, that approach is available now.  I hope to have time to fuss with the GitHub workflow in the coming days.

**Comment by Mihara** [comment]
> I recognize that go install isn't how the shell scripts above work, but if you want an accurate version tag, that approach is available now.

Just an accurate version tag on the executable wouldn't be enough even if I was up to building it from source every time. The repository only contains one release, and it's named "latest", so I wouldn't have anything to compare the accurate version tag to.

**Comment by flwyd** [comment]
If building from source you could check the first item in https://api.github.com/repos/flwyd/adif-multitool/tags that matches `v[0-9].*` and then `go install github.com/flwyd/adif-multitool/adifmt@$tag`.

**Comment by flwyd** [comment]
I've restructured the build and release workflows today, and produced [a release for v0.1.12-rc1](https://github.com/flwyd/adif-multitool/releases/tag/v0.1.12-rc1).  The `adifmt version` command now has the same first line if downloaded from the release or if built via `go install`.  On any pull request or branch push, the "Build and test" workflow will create artifacts for each platform; `adifmt version` for those include the latest tagged semver followed by a hyphen and additional commit details (this is generated by `git describe --dirty`).

Let me know if this matches your expectations.

**Comment by Mihara** [comment]
Thank you, my script works as is now! :+1:
